-- NAP Atlas — plain-English layer. Adds a "plain_summary" column and backfills it
-- for every ingredient/condition we've loaded so far, in everyday language.
-- Additive and idempotent. Safe to re-run.

alter table atlas_entities add column if not exists plain_summary text;

update atlas_entities set plain_summary = 'Insomnia is when you have trouble falling asleep, staying asleep, or waking up feeling rested. It''s incredibly common, especially after service — a lot of veterans deal with restless nights from stress, pain, or a body clock that just got thrown off. Everything below is something people have used, in some cases for centuries, to help settle down for the night.' where slug = 'insomnia';
update atlas_entities set plain_summary = 'Anxiety is that constant sense of worry, tension, or being ''on edge'' that won''t switch off — sometimes with a racing heart or a tight chest. It''s one of the most common things veterans deal with, especially coming home. Everything below is something people across many cultures have turned to for calm — some backed by real modern research, some still just backed by centuries of traditional use.' where slug = 'anxiety';
update atlas_entities set plain_summary = 'Valerian is a root that''s been used since ancient Greece as a natural way to wind down and fall asleep. Modern research is mixed — some studies show it helps a little, others don''t — but it''s been a go-to calming herb for over 2,000 years, and most people tolerate it well.' where slug = 'valerian-root';
update atlas_entities set plain_summary = 'Melatonin is the hormone your own brain already releases at night to tell your body it''s time for sleep — the pill is just a lab-made copy of that same natural chemical. It works best for jet lag or a shifted sleep schedule; its effect on regular insomnia is real, but modest. It''s one of the most-studied sleep aids there is, and it''s generally very safe.' where slug = 'melatonin';
update atlas_entities set plain_summary = 'Magnesium is a mineral your body needs for hundreds of everyday functions, including calming your nervous system — and a lot of people are simply running low without knowing it. The research on magnesium for sleep and stress is promising but still developing; it seems to help most in people who are actually deficient. It''s a well-tolerated, everyday mineral, not an exotic herb.' where slug = 'magnesium-glycinate';
update atlas_entities set plain_summary = 'Chamomile is the same flower in that cup of tea your grandmother probably drank before bed — it''s been used as a calming remedy since ancient Egypt, over 2,000 years ago. Modern studies show a real, modest improvement in sleep quality, and it''s one of the gentlest, safest options here.' where slug = 'chamomile';
update atlas_entities set plain_summary = 'Ashwagandha is a root from India''s traditional medicine (Ayurveda), used for about 3,000 years as an all-purpose ''restore your energy, calm your nerves'' herb — its name literally means ''sleep-inducing.'' It''s one of the better-researched natural options for both sleep and stress, though the studies aren''t considered rock-solid proof yet. Most people tolerate it well short-term, but it''s occasionally been linked to liver issues, so it''s not something to take carelessly or long-term without checking in with a doctor.' where slug = 'ashwagandha';
update atlas_entities set plain_summary = 'L-theanine is a calming compound found naturally in green tea — part of why tea can feel relaxing without making you drowsy. Buddhist monks drank tea for this exact reason, to stay calm and alert while meditating. Research on it for sleep and anxiety shows a real but modest benefit, and it has a very strong safety record.' where slug = 'l-theanine';
update atlas_entities set plain_summary = 'Glycine is a simple building-block amino acid your body already makes and gets from foods like bone broth, gelatin, and meat. Small studies suggest a few grams before bed may help you fall asleep faster and feel more rested — the research is thin, but glycine itself is about as safe and ''normal'' as supplements get.' where slug = 'glycine';
update atlas_entities set plain_summary = 'Hops are the same flower used to brew beer — and for centuries before that, people stuffed pillows with them to fall asleep faster (there''s an old story that this trick helped calm King George III''s insomnia). On its own, the direct evidence is thin, though it''s often paired with other calming herbs like valerian. Considered gentle and safe for short-term use.' where slug = 'hops';
update atlas_entities set plain_summary = 'Passionflower is a climbing vine first used by Aztec healers in Central America as a calming remedy. Three solid modern studies suggest it offers a real, if modest, boost to sleep quality, and it''s generally very well tolerated.' where slug = 'passionflower';
update atlas_entities set plain_summary = 'Lemon balm is a lemony-scented herb from the mint family that ancient Greek physicians used to ''lift the spirits and chase away dark thoughts'' — a description that still fits how people use it today, for calm and easier sleep. Modern research shows a modest, real benefit, and it''s considered safe at normal doses, including as a tea.' where slug = 'lemon-balm';
update atlas_entities set plain_summary = 'Tart cherry — specifically Montmorency cherry juice or extract — is a food-based sleep aid, not a traditional herb. Small studies suggest it may modestly improve sleep, and it naturally contains a bit of melatonin. As a fruit, it''s about as low-risk as natural sleep aids get.' where slug = 'tart-cherry';
update atlas_entities set plain_summary = 'Lavender is the same fragrant purple flower you''d find in a candle or bath oil — the Romans literally used it in their baths (its name comes from the Latin word for ''to wash''). Research on lavender for sleep is genuine but imperfect, with fairly consistent results for calming and easier sleep. Considered gentle and safe.' where slug = 'lavender';
update atlas_entities set plain_summary = 'Jujube seed — known as Suan Zao Ren in Chinese medicine — has been a leading herbal treatment for insomnia in China for close to 1,800 years, especially for sleeplessness that comes with restlessness or worry. Most modern research studies it as part of a traditional herbal formula rather than the seed alone, so it''s promising but not fully proven by itself. It''s been well tolerated in the studies done so far.' where slug = 'ziziphus-jujube';
update atlas_entities set plain_summary = 'Saffron is the world''s most expensive spice — the same one used in paella and Persian cooking — and in Persian traditional medicine it''s long been used to lift low spirits and ease worry. Modern studies show a real, fairly consistent benefit for sleep, and a more modest, mixed one for anxiety specifically. Well tolerated at the small doses used in supplements.' where slug = 'saffron';
update atlas_entities set plain_summary = 'Magnolia bark — called Hou Po in Chinese medicine — has been used for nearly 2,000 years to calm restlessness, ease a tight chest, and help sleep tied to anxious, ''stuck'' feelings. Modern research on it by itself for sleep is still early, but it''s generally considered safe for short-term use.' where slug = 'magnolia-bark';
update atlas_entities set plain_summary = 'Jatamansi is a Himalayan root used in Ayurvedic medicine for about 2,000 years as a calming, sleep-inducing herb, especially for anxiety and restlessness. Modern human research is very limited — really just one small study — so think of this as promising tradition that science hasn''t caught up to yet. It appears well tolerated in the limited data available.' where slug = 'jatamansi';
update atlas_entities set plain_summary = 'California poppy is a wildflower — not the same plant as the opium poppy, and not habit-forming the way that one can be — that Native American tribes in California used as a gentle way to ease into sleep and calm pain. On its own there''s essentially no direct modern research; what evidence exists comes from combination products with other herbs, so it''s hard to say how much the poppy itself is doing. Considered gentle and mild.' where slug = 'california-poppy';
update atlas_entities set plain_summary = 'Kava is a root from the South Pacific islands, used for thousands of years in ceremonies and everyday life to relax, ease tension, and bring people together socially — kind of the traditional equivalent of sharing a drink to unwind. Modern research on kava for anxiety is genuinely mixed, and it''s important to know it carries a real, if rare, risk of serious liver damage. This is not a casual, risk-free supplement — anyone with liver issues should avoid it, and it''s worth talking to a doctor before trying it.' where slug = 'kava';
update atlas_entities set plain_summary = 'Rhodiola is an Arctic root long used in Russian and Eastern European folk medicine to help the body handle stress, fatigue, and exhaustion — it''s a classic ''adaptogen,'' meant to help you adapt to strain rather than treat one specific problem. Research on it for anxiety specifically is still early and not strong enough to call it proven. Generally considered well tolerated.' where slug = 'rhodiola-rosea';
update atlas_entities set plain_summary = 'Holy basil, or Tulsi, is considered one of the most sacred plants in Ayurvedic medicine — sometimes called ''the elixir of life'' — traditionally taken daily as a tea for calm and clarity of mind. Modern research on it for stress is real but still developing, and most studies come from the companies that sell it, so more independent research would help confirm it. Generally well tolerated.' where slug = 'holy-basil-tulsi';
update atlas_entities set plain_summary = 'Bacopa, also called Brahmi, is an Ayurvedic herb traditionally used to calm a restless mind and support memory and focus — most of its serious modern research is actually about memory, with calming effects showing up as a side note rather than the main focus. Generally well tolerated in studies lasting several months.' where slug = 'bacopa-monnieri';
update atlas_entities set plain_summary = 'Kanna is a succulent plant from southern Africa that Indigenous San and Khoikhoi communities have chewed, smoked, or brewed for centuries to lift mood and ease stress and tension. Modern research is early — mostly small studies in healthy volunteers rather than people with diagnosed anxiety — so it''s promising, but not proven yet.' where slug = 'kanna-sceletium';
update atlas_entities set plain_summary = 'Galphimia glauca is a Mexican plant long used to treat ''nervios'' and ''susto'' (fright) — a fear or shock reaction recognized in traditional Mexican medicine. Unusually for a plant on this list, it''s actually been tested in several solid modern clinical trials for anxiety, and the results are genuinely encouraging. It''s meant to be taken daily, not as a quick fix in the moment.' where slug = 'galphimia-glauca';
update atlas_entities set plain_summary = 'Inositol is a naturally occurring, sugar-like compound your body already makes and uses in nerve signaling — technically it''s not even a vitamin, though it was once mistakenly called one. The anxiety research is old and comes from very small studies out of one research group decades ago, so it''s an interesting lead rather than solid proof. Well tolerated even at the fairly high doses used in studies.' where slug = 'inositol';
